apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstonefola
  labels:
    app: capstonefola
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstonefola
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstonefola
    spec:
      containers:
        - image: folasade/capstonefola
          imagePullPolicy: Always
          name: capstonefola
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: capstonefola
  labels:
    app: capstonefola
spec:
  type: LoadBalancer
  selector:
    app: capstonefola
  ports: 
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
